### ISSUE TITLE
Removing duplicates from a unique source of data

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DIVAnd.jl#107]
[User email added here so users can find the answer]

Regarding, finding and removing the duplicate observations, in the notebook "90-full-analysis", section 3.2,  it seems that the function uses two data files:

@time dupl = DIVAnd.Quadtrees.checkduplicates(
    (obslon,obslat,obsdepth,obstime), obsval, 
    (obslonwod,obslatwod, obsdepthwod, obstimewod), obsvalwod,
    (0.01,0.01,0.01,1/(24*60)),0.01);

But, if I want to remove duplicates from one file, how can I do that ?

**Comment by ctroupin** [comment]
The function [`checkduplicates`](https://github.com/gher-uliege/DIVAnd.jl/blob/master/src/Quadtrees.jl#L526)
can be used directly on data from a single dataset, i.e. with a command like
```julia
dupl = checkduplicates((obslon,obslat,obsdepth,obstime), obsval, delta, deltavalue)
```

**Comment by Alexander-Barth** [comment]
Yes, I can confirm that this is the correct function to be used in this case.
