### ISSUE TITLE
OutOfMemoryError()  error in Black Sea product

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DIVAnd.jl#110]
![error](https://user-images.githubusercontent.com/11868914/203060567-9c21b1ee-e983-40f8-9ee6-47e35f199e51.png)
✉️ from a user:

I try to run divand for all seasons, and I got an error: OutOfMemoryError() 

Variable : Water body dissolved oxygen concentration
```julia
dx=dy=0.01
lonr=26.5:dx:42 # Black Sea + Marmara
latr=40:dy:48
monthlists = [[12,1,2],[3,4,5],[6,7,8],[9,10,11]]
year_start=1970:2016
year_window = 6
depthr = [0.,5.,10.,20.,30.,40., 50.,75.,100.,125.,150., 200.,250.];
lenxym = fill(96000.,(length(depthr),4))
lenz = fill(100.,(length(depthr),4)) 
```
I increase the value of `memtofit` from 100 to 1000, but no change.

My machine:
```
Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz   2.90 GHz
RAM: 16 GB
```

**Comment by jmbeckers** [comment]
depthr = [[0.,5.,10.,20.,30.,40., 50.,75.,100.,125.,150).,200.,250.];

Is this really coming from the actual code or just a cut/paste problem? Clearly depthr defined in this way cannot be correct

**Comment by ctroupin** [comment]
Clearly an issue in the copy/paste (the list was somehow interpreted as a phone number and some "call to" text came in the copied text)
