### ISSUE TITLE
[🐞] When running DIVAnd, artifacts appear which seem to be linked to the bathymetry

### ISSUE THREAD

**Issue by qcazenave** [gher-uliege/DIVAnd.jl#123]
No problem with running DIVAnd so I am not sure whether the "bug" type is relevant.

My problem is that when looking at the maps generated by diva3d, we noticed some gradients that seem to exactly correspond to change in the bottom depth as if information from below were transmitted to the layer above but not spread over nearby regions where there is no information available from below since it is already the bottom depth... Is there a way to suppress this effect ?

Below is the way we run diva3d as well as an example of the ouput maps, first without and then, with the isobaths :

`mask = falses(size(b,1),size(b,2),length(depthr)); #b is bathymetry obtained with the "extract_bath" function
for k = 1:length(depthr)
    mask[:,:,k] .= (b .>= depthr[k])
end;

dbinfo = diva3d((lonr,latr,depthr,TS),
    (obslon,obslat,obsdepth,obstime),
    obsval,
    (lenx,leny,lenz2),
    epsilon2,
    filename,varname,
    bathname = bathname,
    bathisglobal = bathisglobal,
    mask=mask,
    #plotres = plotres_timeindex,
    ncvarattrib = ncvarattrib,
    ncglobalattrib = ncglobalattrib,
    timeorigin = timeorigin,
    transform = Anam.loglin(slog),
    memtofit = 100
    )`

![image](https://user-images.githubusercontent.com/118441818/215136437-85219455-87b0-4e75-b476-ce6d51ccf138.png)
![image](https://user-images.githubusercontent.com/118441818/215136536-82277b9d-da7d-4181-b0c8-900b147749e3.png)

**Comment by jmbeckers** [comment]
Can you try with `;alphabc=0`

**Comment by qcazenave** [comment]
I tried with alphabc = 0 but it does not change the result. I don't really understand what this parameters does, nor what youn mean by "do you see the output proceeding by windows moving upward ?"
Sorry :/

**Comment by jmbeckers** [comment]
alphabc changes the way boundary conditions are applied at the edges of the domain.
What I mean with the windows moving upward is the output of diva3d which tells you something like
```
Info: number of windows: 
```
and if you have more than 1 window it means a domain decomposition is at work.

**Comment by jmbeckers** [comment]
> I tried with alphabc = 0 but it does not change the result. 

Not even on the near bottom layers (I mean not necessarily correcting the artefacts but slightly changing values) ?

**Comment by qcazenave** [comment]
Ok... then it says : Info: number of windows: 1 with alphabc=0 (but it said the same with the default parameterization...)

**Comment by qcazenave** [comment]
> 

It looks extremely similar to me... visually (I will take a look at the absolut difference to be sure

**Comment by qcazenave** [comment]
OK my mistake, I went too fast, it is indeed different.

**Comment by jmbeckers** [comment]
> OK my mistake, I went too fast, it is indeed different.

But not eliminating the artefacts ?

**Comment by qcazenave** [comment]
unfortunately not...

![image](https://user-images.githubusercontent.com/118441818/215493152-a67d1cbc-ef18-489c-87ea-310e5cc3c59d.png)

**Comment by jmbeckers** [comment]
Thanks for the plots (I assume the dots on the vertical indicate the grid position on the vertical). So it is not even a layer closest to the  "bottom".  Very strange. Would it be possible to share the setup (or better a simplified one, for example same grid but toy data where the problem still exists) ?

**Comment by jmbeckers** [comment]
Can you also have a look at a vertical section at -3 longitude ?

**Comment by qcazenave** [comment]
Plots are done afterwards with a netcdf reading (pyplot): it is a map (lon,lat) fo the field at 75m deep (depth levels are from 0 to 125m and the last 3 layers are 75, 100 and 125m) but this artefact is visible at other depths as well, above and below (at 40m, you can even see the isobaths 50m and 75m in the field features).
The features are also visible on panoply but it is not that obvious (due to the different colormaps, probably...).
I will have a look at the cross section.

**Comment by jmbeckers** [comment]
> Plots are done afterwards with a netcdf reading (pyplot): it is a map (lon,lat) fo the field at 75m deep (depth levels are from 0 to 125m and the last 3 layers are 75, 100 and 125m) but this artefact is visible at other depths as well, above and below (at 40m, you can even see the isobaths 50m and 75m in the field features). The features are also visible on panoply but it is not that obvious (due to the different colormaps, probably...). I will have a look at the cross section.

Can you do the plots within diva3d with `plotres to exclude the possibility of a problem when creating the netcdf file ? That would make sure the artefact is due to the analysis itself.

**Comment by Alexander-Barth** [comment]
Can you also make a plot of the background profile  `dbinfo[:background_profile]` (2d array:  depth x time) and what is the vertical correlation length?

**Comment by qcazenave** [comment]
Result of plotres :

![image](https://user-images.githubusercontent.com/118441818/215734717-28fd58e6-d9ca-423f-b37d-0c0eb30d6dcb.png)

**Comment by jmbeckers** [comment]
Thanks for the effort. So definitively due to the analysis itself.

**Comment by qcazenave** [comment]
background profiles (I don't understand the values: why 5 when the final O2 concentration values are around 200) :

![image](https://user-images.githubusercontent.com/118441818/215755177-aa34d6f2-c2b1-42a5-9a00-ad2d868ee345.png)

**Comment by jmbeckers** [comment]
Log transformation via anamorphosis ?

**Comment by jmbeckers** [comment]
I try to recreate something similar with a toy example. The only situation where I could recreate something into this direction is a situation with a strong vertical gradient, low vertical resolution and large vertical correlation length.

What is lenz2 in your case ?

**Comment by qcazenave** [comment]
Yeas, sorry I forgot to give you the vertical correlation length

Lenz 
![image](https://user-images.githubusercontent.com/118441818/215765228-20137f1d-f1e5-475c-bcbe-3be683f3c0fc.png)

Vertical resolution
![image](https://user-images.githubusercontent.com/118441818/215765388-5e228a6a-36c2-438f-b070-e7fa41920b04.png)

**Comment by jmbeckers** [comment]
Well then I think the vertical length scale is definitively too high ! You basically ask to mix the whole water column which then naturally leads to steps above places where the topography changes.

**Comment by qcazenave** [comment]
So I used a new vertical correlation length (see image below) the maps are different but the effect is still visible.

![image](https://user-images.githubusercontent.com/118441818/215806581-ea810345-015d-419a-9049-7127ba49b866.png)


![image](https://user-images.githubusercontent.com/118441818/215806486-871a592a-01c1-4122-ae67-4849263e5b9f.png)

**Comment by qcazenave** [comment]
Vertical cross-section:
![image](https://user-images.githubusercontent.com/118441818/215807259-1a56573c-2bb2-48e9-8be6-3632ebcc8363.png)

**Comment by jmbeckers** [comment]
Vertical sections actually seem quite ok but they also show the lack of vertical resolution of the grid compared to the horizontal resolution. There are large regions of flat topography simply due to lack of vertical resolution. 
So my approach would use higher vertical resolution (and possible even smaller vertical correlation length; with 50m you still mix a lot near the bottom)

**Comment by qcazenave** [comment]
OK, I thought we had to use correlation length = min(2*dz) which is why for the deepest layers the correlation length is 50m (resolution = 25m from 50m to 125m)

**Comment by jmbeckers** [comment]
> 



> OK, I thought we had to use correlation length = min(2*dz) which is why for the deepest layers the correlation length is 50m (resolution = 25m from 50m to 125m)

Yep, that is also why I suggest to increase resolution :-)

**Comment by jmbeckers** [comment]
Unless proved differently, I think we can consider that the artefacts are due to coarse vertical resolution, (too) large vertical resolution in a stratified situation. I do not think that we can provide corrections to that other than increasing resolution and I would close the topic for the time being. Comments can still be added of course.

For DIVAnd I suggest to
a) adapt the background field information by applying the inverse transformation
b) add some sanity checks in vertical correlation length by show a warning if it's value is close to the domain size

**Comment by qcazenave** [comment]
Hi, coming back to you.
So I need to increase the vertical resolution, OK.
But then if I want the correlation length (horizontal or vertical) to be determined with fitlen, I get an error because there is not enough data in the region compared to the vertical resolution:

![image](https://user-images.githubusercontent.com/118441818/216021010-02563888-84ca-4feb-a10c-644aa9f305d8.png)

apparently, the fithorzlen function cannot deal with an empty "fitinfos" output from ther fitlen function...

Is there an option to prevent this error from happening ?

**Comment by jmbeckers** [comment]
Can you run with
```
ENV["JULIA_DEBUG"] = "DIVAnd".
```
Do you see an output of fitting which works well near the surface and then fails in deeper parts ?

**Comment by qcazenave** [comment]
Yes, it only fails for deeper parts (below 75m)
Ok I will run with the 2 different resolutions but an imposed L to confirm it works better.

**Comment by jmbeckers** [comment]
Normally when there is a problem in one layer, there is a vertical filtering of the estimations later anyway. It seems that it however request the :rqual to be set, which is not the case when there is no data at all.

So 

we would need to add 
```
dbinfo = Dict{Symbol,Any}(
        :covar => covar,
        :fitcovar => fitcovar,
        :distx => distx,
        :rqual => rqual,
        :range => range,
        :covarweight => covarweight,
        :distx => distx,
        :sn => SN,
        :meandist => meandist,
    )
```
instead of the empty Dict{Symbol,Any}() when catching


https://github.com/gher-uliege/DIVAnd.jl/blob/df4b25bbf92988f61333e943ebf322a313456c2d/src/fit.jl#L428

And using the dict with appropriate default values when there are not data. Then the vertical filtering should be able to proceed.

**Comment by jmbeckers** [comment]
Now until the fix is implemented and tested, for your case, I would suggest to only fit down to 70m and once happy with it, copy the values of the correlation length scale found at 70m into the deeper layers (since you have anyway very few data, that seems a reasonable assumption)

**Comment by qcazenave** [comment]
I tried with a finer resolution (32 depth levels : depth = [0:2:20 ..., 25:5:125 ...] ) and I get: Unhandled Task ERROR: SuiteSparse.CHOLMOD.CHOLMODException("out of memory")
T-T
With 22 depth levels, it worked. I would say that the results are similar in the way that the transition is still visible but it is less obvious since the gap between 2 successive layers is smaller so the transition is closer to the layer boundary.

I don't know if it is a big problem since it is not that visible (but I could also see the same effect at the bottom layers of the Atlantique domain) and no one said anything about it during the previous EMODNET phases (we checked and the artifact was already there on the Loire DIVAnd maps of phase 4 but had remained unnoticed...)

In case you are interested, I'll join to the current message
- the netcdf file with the observations used
- the bathymetry file
- the notebook
[test_Loire.zip](https://github.com/gher-uliege/DIVAnd.jl/files/10569880/test_Loire.zip)
