### ISSUE TITLE
'data access' and 'WEB_visualisation' attributes not correct anymore

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DIVAnd.jl#130]
It seems those attributes are not valid anymore, for example:

https://github.com/gher-uliege/DIVAnd.jl/blob/6a7be8f2f6787b9eb0a433db34d832b62b3af2e3/src/SDNMetadata.jl#L8-L11
due to the move to the Central Portal.

A user reported that they cannot change those values "manually" in their script for the generation of new products (haven't checked yet).

**Comment by Alexander-Barth** [comment]
This should be address by these commits:

commit e2863a511e73c76afe28535b30cf7b10bf0c7e42 
commit 603c65d58d462de095a94227f7d884edbe53ed83
commit d6cb1dca13f26ba01e2748594c5558e271fa50c8

(we also now test EMODnet Chemistry, rather than SeaDataCloud)

**Comment by qcazenave** [comment]
Hi, I would just like to comment that it is in fact possible to change those values manually. At least on my side, I did not have these attributes in the output file. I did not use the SDNMetadata function so maybe this explains that...?
