### ISSUE TITLE
Does anyone have a MATLAB version ?

### ISSUE THREAD

**Issue by Fanningjin** [gher-uliege/DIVAnd.jl#146]
I did a MATLAB-based program before, and the URL provided in the article seems to be the MATLAB version of the program package, but the website can no longer be opened,

BARTH A, BECKERS J M, TROUPIN C, et al. divand-1.0: n-dimensional variational data analysis for ocean observations[J/OL]. Geoscientific Model Development, 2014, 7(1): 225-241. DOI:[10.5194/gmd-7-225-2014](https://doi.org/10.5194/gmd-7-225-2014).

http://modb.oce.ulg.ac. be/mediawiki/index.php/divand

And in the search on the Internet there are posts under which people say that the URL can no longer be opened, and can not search for the MATLAB version of the program package, may I ask if anyone has saved the MATLAB version of the program package?

Many thanks.

Jin

**Comment by ctroupin** [comment]
Dear Jin,
the server where the Matlab version was made available is not working anymore, but also the Matlab version of the code is not maintained anymore since many years ago, we really recommend to use the present version, which is in Julia (quite similar to Matlab in the syntax etc).

**Comment by Fanningjin** [comment]
Dear ctroupin,
Thanks for your reply. Knowing this I'll stop looking for it and I'll use the current version.
