### ISSUE TITLE
advection constrain

### ISSUE THREAD

**Issue by JianghuiDu** [gher-uliege/DIVAnd.jl#47]
I read from the paper that the degree of advection constrain can be varied using a parameter but I couldn't find how to specifiy/tune this parameter in the documentation/examples. `DIVAndrun` accepts a `velocity` argument but not a parameter for this constrain.

**Comment by jmbeckers** [comment]
I'm not on my main computer and cannot check, but I think in DIVAnd you can simply change the intensity of the velocity field. We will try to add a notebook with examples.

**Comment by JianghuiDu** [comment]
Like multiply the velocity components with a constant? Is there a way to optimize the parameter?

**Comment by Alexander-Barth** [comment]
Yes, this is correct. Increasing the advection constrain, is achieved by scaling it up:

```julia
scale = 2.
DIVAndrun(mask,(pm,pn),(xi,yi),(x,y),f,len,epsilon2; velocity = (scale * u,scale * v))
```

**Comment by Alexander-Barth** [comment]
> ... Is there a way to optimize the parameter?

There is no tool in DIVAnd.jl to optimize this parameter. But one can do this with cross-validation by calling DIVAnd with different values of `scale` and comparing the analysis RMS error with a validation dataset.

**Comment by jmbeckers** [comment]
If you are brave and you do not have a sufficiently large data set from which to set aside a validation set, you can try to understand how DIVAnd_cv works and adapt it to optimize the "scale" value; but the method(s) rely on quite some hypothesis which are difficult to control and you might end up tuning the parameter by "hand".

**Comment by JianghuiDu** [comment]
Understood. I will do some tests. Thanks!

**Comment by JianghuiDu** [comment]
More questions about the `velocity` in `DIVAndrun`:
1. is it a tuple of `(u,v)` or `(v, u)`? My `(xi,yi)` are `(lat,lon)` and I feel the result using `(u,v)` is not consistent with my intuition...
2. `velocity` is defined on analysis grid rather than observation locations, right?

**Comment by jmbeckers** [comment]
1) u is along the direction of the first coordinate, v in the direction of the second coordinate  etc. If you decide to use latitude as first coordinate , u would be the meridional velocity

2) yes, defined on the analysis grid. If you have it on another grid, you can use DIVAnd to interpolate ;-).

**Comment by JianghuiDu** [comment]
Thanks for answering these questions. It would be nice if those things are in the documentations.

**Comment by jmbeckers** [comment]
Maybe we still need some advice on how to roughly estimate the scale for velocities, or in other words how to estimate the penalzation importance compared to other penalizations ?

**Comment by JianghuiDu** [comment]
Yes. That's my question in the other thread. In my case adding advection constrain only increases the root mean square, but it has an (flipped) L shape that until certain point increasing `scale` has minimal impact on RMS, but still appears to affect the analysis results visually. I feel it still makes sense to add advection constrain because my data is really sparse, but to what point is my question. That's why I'd like to know the costs due to advection relative to the other constrains.

**Comment by jmbeckers** [comment]
http://localhost:8888/notebooks/Documents/GitHub/Diva-Workshops/notebooks/5-AdvancedTopics/advection_constraint_Adriatic.ipynb

For an example how to scale the constraint
